"""
Principled denoising training for feasibility-preserving diffusion.

This implements the PROPER discrete denoising diffusion objective:

  Forward process:
    Given a clean tour x_0, apply T random 2-opt swaps to get x_T.
    Record the full trajectory and which swap was applied at each step.

  Training objective:
    Given (x_t, t), predict which swap was applied at step t.
    Equivalently: predict how to reverse the last noise step.
    Since 2-opt is an involution (applying the same swap undoes it),
    predicting the applied swap = predicting how to denoise.

  Inference:
    Start from random tour x_T. For t = T, T-1, ..., 1:
    model predicts swap → apply it → one step closer to clean tour.

This is the discrete analog of DDPM's "predict the noise ε" objective.

Label-free: x_0 is generated by greedy 2-opt (no external solver).
The label (which swap was applied) comes from the forward process itself.

Usage:
    python -m training.denoise_trainer --N 50 --device cuda:0
    python -m training.denoise_trainer --N 50 --device cuda:0 --train_data path/to/edisco_data.txt
"""

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

import argparse
import time
import numpy as np
import torch
import torch.nn.functional as F
from tqdm import tqdm

from problems.tsp.tour import (
    enumerate_2opt, apply_2opt, delta_2opt, tour_cost,
    dist_matrix_from_coords, random_tour, is_valid_tour,
    greedy_nearest_neighbor,
)
from problems.tsp.data import generate_instance, solve_2opt
from models.move_scorer import MoveScorer


def generate_clean_tours(N, n_instances, seed=42):
    """Generate instances + locally-optimal tours via greedy 2-opt.

    This is fully self-contained — no external solver.
    The tours serve as x_0 (clean starting points) for the forward process.
    """
    print(f"Generating {n_instances} TSP-{N} instances + 2-opt solutions...")
    t0 = time.time()
    coords_list, dist_list, tour_list, cost_list = [], [], [], []
    for i in range(n_instances):
        coords = generate_instance(N, seed=seed + i)
        dist = dist_matrix_from_coords(coords)
        tour, cost = solve_2opt(coords, max_restarts=3)
        coords_list.append(coords)
        dist_list.append(dist)
        tour_list.append(tour)
        cost_list.append(cost)
    elapsed = time.time() - t0
    print(f"  Done in {elapsed:.1f}s. Avg cost: {np.mean(cost_list):.4f}")
    return coords_list, dist_list, tour_list, cost_list


def make_denoise_sample(x0, dist, moves_list, M, T_max):
    """Generate one denoising training sample via trajectory reversal.

    1. Start from clean tour x0
    2. Apply T random 2-opt swaps (T ~ U[1, T_max])
    3. Record which swap was applied at each step
    4. Pick random timestep t — label = swap applied at step t

    Returns:
        x_t: (N,) scrambled tour at timestep t
        t: int, timestep (1-indexed)
        T: int, total forward steps applied
        label: int, index into moves_list of the swap that was applied
    """
    N = len(x0)
    T = np.random.randint(1, T_max + 1)

    # Forward: apply T random swaps, record each
    tour = x0.copy()
    applied = []
    for step in range(T):
        swap_idx = np.random.randint(M)
        i, j = moves_list[swap_idx]
        tour = apply_2opt(tour, i, j)
        applied.append(swap_idx)

    # Pick a random timestep to train on
    t = np.random.randint(0, T)  # 0-indexed into applied list
    label = applied[t]

    # Reconstruct x_t (the state AFTER applying swap at step t)
    # x_t = x0 with first (t+1) swaps applied
    x_t = x0.copy()
    for step in range(t + 1):
        i, j = moves_list[applied[step]]
        x_t = apply_2opt(x_t, i, j)

    # Timestep for the model: how many swaps have been applied (1-indexed)
    timestep = t + 1

    return x_t, timestep, T_max, label


@torch.no_grad()
def denoise_inference(model, coords_t, dist_np, moves_ij, N, T,
                      T_max, device, n_trajectories=1):
    """Run reverse denoising: start from random tour, apply T predicted swaps.

    With n_trajectories > 1: run multiple independent reverse trajectories
    and return the best final tour (POMO-style multi-sampling).

    Returns:
        best_tour: (N,) numpy array
        best_cost: float
    """
    model.eval()
    moves_list = moves_ij.cpu().numpy().tolist()

    best_tour = None
    best_cost = float('inf')

    for _ in range(n_trajectories):
        tour_np = random_tour(N)

        for step in range(T):
            # Timestep: counting down from T to 1
            t_val = T - step

            tour_t = torch.tensor(tour_np, dtype=torch.long, device=device).unsqueeze(0)
            t_tensor = torch.tensor([t_val], dtype=torch.float32, device=device)

            scores = model(coords_t, tour_t, t_tensor, float(T_max), moves_ij)
            best_idx = scores.argmax(dim=-1).item()
            i, j = moves_list[best_idx]

            tour_np = apply_2opt(tour_np, i, j)

        cost = tour_cost(tour_np, dist_np)
        if cost < best_cost:
            best_cost = cost
            best_tour = tour_np.copy()

    return best_tour, best_cost


def evaluate(model, coords_list, dist_list, ref_costs, moves_ij, N,
             T, T_max, device, n_eval=None, n_trajectories=1):
    """Evaluate via denoising inference."""
    model.eval()
    if n_eval is None:
        n_eval = len(coords_list)
    n_eval = min(n_eval, len(coords_list))

    costs, gaps = [], []
    for idx in range(n_eval):
        coords_t = torch.tensor(
            coords_list[idx], dtype=torch.float32, device=device
        ).unsqueeze(0)

        final_tour, final_cost = denoise_inference(
            model, coords_t, dist_list[idx], moves_ij, N,
            T=T, T_max=T_max, device=device,
            n_trajectories=n_trajectories,
        )
        assert is_valid_tour(final_tour), "Denoised tour is infeasible!"

        costs.append(final_cost)
        gaps.append(final_cost / ref_costs[idx] - 1.0)

    return np.mean(costs), np.mean(gaps)


def train(args):
    device = torch.device(args.device)
    N = args.N
    T_max = args.T_max if args.T_max else N * 5
    T_infer = args.T_infer if args.T_infer else N * 3

    # Precompute move list
    moves_list = enumerate_2opt(N)
    M = len(moves_list)
    moves_ij = torch.tensor(moves_list, dtype=torch.long, device=device)
    print(f"TSP-{N}: {M} valid 2-opt moves, T_max={T_max}, T_infer={T_infer}")

    # Generate clean tours (x_0) — fully self-contained
    if args.train_data:
        from problems.tsp.edisco_data import load_edisco_tsp
        coords_train, dist_train, tour_train, cost_train = load_edisco_tsp(
            args.train_data, max_instances=args.n_train
        )
    else:
        coords_train, dist_train, tour_train, cost_train = generate_clean_tours(
            N, args.n_train, seed=42,
        )

    # Validation (always self-generated for consistency)
    if args.val_data:
        from problems.tsp.edisco_data import load_edisco_tsp
        coords_val, dist_val, tour_val, cost_val = load_edisco_tsp(
            args.val_data, max_instances=args.n_val
        )
    else:
        coords_val, dist_val, tour_val, cost_val = generate_clean_tours(
            N, args.n_val, seed=99999,
        )

    # Model
    model = MoveScorer(
        n_node_features=5,
        hidden_dim=args.hidden_dim,
        n_layers=args.n_layers,
    ).to(device)
    n_params = sum(p.numel() for p in model.parameters())
    print(f"MoveScorer: {n_params:,} parameters")

    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.n_epochs,
    )

    # Baselines
    n_val_actual = len(dist_val)
    random_costs = [
        np.mean([tour_cost(random_tour(N), dist_val[i]) for _ in range(10)])
        for i in range(n_val_actual)
    ]
    print(f"Baselines: reference={np.mean(cost_val):.4f}, "
          f"random={np.mean(random_costs):.4f} "
          f"(ratio={np.mean(random_costs)/np.mean(cost_val):.2f}x) "
          f"[{n_val_actual} val instances]")

    os.makedirs(args.ckpt_dir, exist_ok=True)
    best_gap = float('inf')

    for epoch in range(1, args.n_epochs + 1):
        model.train()
        epoch_loss = 0.0
        epoch_acc = 0.0

        pbar = tqdm(range(args.steps_per_epoch), desc=f"Epoch {epoch}")
        for step in pbar:
            batch_tours, batch_coords, batch_labels, batch_t = [], [], [], []

            for _ in range(args.batch_size):
                idx = np.random.randint(len(coords_train))
                x_t, t, t_max_val, label = make_denoise_sample(
                    tour_train[idx], dist_train[idx], moves_list, M, T_max,
                )
                batch_tours.append(x_t)
                batch_coords.append(coords_train[idx])
                batch_labels.append(label)
                batch_t.append(t)

            coords_t = torch.tensor(np.stack(batch_coords), dtype=torch.float32, device=device)
            tours_t = torch.tensor(np.stack(batch_tours), dtype=torch.long, device=device)
            labels_t = torch.tensor(batch_labels, dtype=torch.long, device=device)
            t_tensor = torch.tensor(batch_t, dtype=torch.float32, device=device)

            scores = model(coords_t, tours_t, t_tensor, float(T_max), moves_ij)
            loss = F.cross_entropy(scores, labels_t)

            preds = scores.argmax(dim=-1)
            acc = (preds == labels_t).float().mean().item()

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            epoch_loss += loss.item()
            epoch_acc += acc
            pbar.set_postfix(loss=f"{loss.item():.3f}", acc=f"{acc:.2%}")

        scheduler.step()
        avg_loss = epoch_loss / args.steps_per_epoch
        avg_acc = epoch_acc / args.steps_per_epoch
        print(f"Epoch {epoch}: loss={avg_loss:.4f}, acc={avg_acc:.2%}")

        if epoch % args.eval_freq == 0:
            avg_cost, avg_gap = evaluate(
                model, coords_val, dist_val, cost_val,
                moves_ij, N, T=T_infer, T_max=T_max,
                device=device, n_eval=args.n_eval,
                n_trajectories=args.n_trajectories,
            )
            print(f"  Eval: cost={avg_cost:.4f}, gap={avg_gap:.2%} "
                  f"(ref={np.mean(cost_val):.4f}, {args.n_trajectories} trajectories)")

            if avg_gap < best_gap:
                best_gap = avg_gap
                path = os.path.join(args.ckpt_dir, f'best_tsp{N}.pt')
                torch.save({
                    'epoch': epoch,
                    'model_state_dict': model.state_dict(),
                    'gap': avg_gap,
                    'cost': avg_cost,
                    'args': vars(args),
                }, path)
                print(f"  [checkpoint] best gap={avg_gap:.2%} -> {path}")

    print(f"\nTraining complete. Best gap: {best_gap:.2%}")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Denoising training for feasibility-preserving TSP diffusion')
    parser.add_argument('--N', type=int, default=20)
    parser.add_argument('--n_train', type=int, default=5000)
    parser.add_argument('--n_val', type=int, default=100)
    parser.add_argument('--batch_size', type=int, default=64)
    parser.add_argument('--n_epochs', type=int, default=50)
    parser.add_argument('--steps_per_epoch', type=int, default=200)
    parser.add_argument('--lr', type=float, default=3e-4)
    parser.add_argument('--hidden_dim', type=int, default=64)
    parser.add_argument('--n_layers', type=int, default=4)
    parser.add_argument('--T_max', type=int, default=None,
                        help='Max forward scrambling steps (default: 5*N)')
    parser.add_argument('--T_infer', type=int, default=None,
                        help='Denoising steps at inference (default: 3*N)')
    parser.add_argument('--n_trajectories', type=int, default=1,
                        help='Number of parallel denoising trajectories at eval (best-of-K)')
    parser.add_argument('--eval_freq', type=int, default=5)
    parser.add_argument('--n_eval', type=int, default=50)
    parser.add_argument('--device', type=str, default='cpu')
    parser.add_argument('--ckpt_dir', type=str, default='./checkpoints/denoise')
    parser.add_argument('--train_data', type=str, default=None,
                        help='EDISCO-format training data (optional; if omitted, generates via 2-opt)')
    parser.add_argument('--val_data', type=str, default=None,
                        help='EDISCO-format validation data (optional)')
    args = parser.parse_args()
    train(args)
